export const PERMISSIONS = {
  CUSTOMER: {
    CREATE: 'CUSTOMER_CREATE',
    READ: 'CUSTOMER_READ',
    UPDATE: 'CUSTOMER_UPDATE',
    DELETE: 'CUSTOMER_DELETE'
  },
  PROJECT: {
    CREATE: 'PROJECT_CREATE',
    READ: 'PROJECT_READ',
    UPDATE: 'PROJECT_UPDATE',
    DELETE: 'PROJECT_DELETE'
  },
  TIMESHEET: {
    CREATE: 'TIMESHEET_CREATE',
    READ: 'TIMESHEET_READ',
    UPDATE: 'TIMESHEET_UPDATE',
    DELETE: 'TIMESHEET_DELETE',
    SUBMIT: 'TIMESHEET_SUBMIT',
    REVIEW: 'TIMESHEET_REVIEW'
  },
  TIMESHEET_DETAIL: {
    CREATE: 'TIMESHEET_DETAIL_CREATE',
    READ: 'TIMESHEET_DETAIL_READ',
    UPDATE: 'TIMESHEET_DETAIL_UPDATE',
    DELETE: 'TIMESHEET_DETAIL_DELETE'
  },
  TIMEOFF: {
    CREATE: 'TIMEOFF_CREATE',
    READ: 'TIMEOFF_READ',
    UPDATE: 'TIMEOFF_UPDATE',
    DELETE: 'TIMEOFF_DELETE'
  },
  AUDIT: {
    CREATE: 'AUDIT_CREATE',
    READ: 'AUDIT_READ',
    UPDATE: 'AUDIT_UPDATE',
    DELETE: 'AUDIT_DELETE'
  },
  JOBDETAILSENTITY: {
    CREATE: 'JOBDETAILSENTITY_CREATE',
    READ: 'JOBDETAILSENTITY_READ',
    UPDATE: 'JOBDETAILSENTITY_UPDATE',
    DELETE: 'JOBDETAILSENTITY_DELETE'
  },
  TRIGGERDETAILSENTITY: {
    CREATE: 'TRIGGERDETAILSENTITY_CREATE',
    READ: 'TRIGGERDETAILSENTITY_READ',
    UPDATE: 'TRIGGERDETAILSENTITY_UPDATE',
    DELETE: 'TRIGGERDETAILSENTITY_DELETE'
  }
};
